package online_school.enum_enum;

public enum Role {
    COURSE, LECTURE, TEACHER, STUDENT, COURSE_DATA,
    COURSE_INFO, LECTURE_INFO, STUDENT_INFO,
    TEACHER_INFO, SHOW_COURSE, SHOW_LECTURE,
    SHOW_TEACHER, SHOW_STUDENT, DELETE_COURSE,
    DELETE_LECTURE, DELETE_TEACHER, DELETE_STUDENT, TEACHER_FOR_LECTURE,
    STOP, LECTURE_DATA, STUDENT_FOR_LECTURE, ADD, ERROR
}
